# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OQHDRDE0rYaOIhCpjXcV-zRlNvt6pBIr
"""

!pip install librosa

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import streamlit.components.v1 as components
# 
# # Konfigurasi Halaman (Hanya boleh dipanggil sekali di paling atas)
# st.set_page_config(page_title="TranscribX - Enterprise AI", layout="wide")
# 
# # 1. INISIALISASI SESSION STATE UNTUK LOGIN
# if "logged_in" not in st.session_state:
#     st.session_state["logged_in"] = False
# 
# # 2. LOGIKA JIKA BELUM LOGIN (TAMPILKAN FORM)
# if not st.session_state["logged_in"]:
#     # Desain tampilan halaman login di tengah
#     col1, col2, col3 = st.columns([1, 2, 1])
#     with col2:
#         st.write("")
#         st.write("")
#         st.markdown("<h2 style='text-align: center;'>🔒 Login TranscribX Enterprise</h2>", unsafe_allow_html=True)
#         st.markdown("<p style='text-align: center; color: #64748b;'>Silakan masukkan kredensial untuk mengakses sistem Notulensi AI.</p>", unsafe_allow_html=True)
# 
#         # Form Login
#         with st.form("login_form"):
#             username = st.text_input("Username", placeholder="Masukkan admin")
#             password = st.text_input("Password", type="password", placeholder="Masukkan 12345")
#             submit_button = st.form_submit_button("🚀 Masuk ke Sistem", use_container_width=True)
# 
#             if submit_button:
#                 # Kredensial statis (Bisa kamu ganti username & password-nya di sini)
#                 if username == "admin" and password == "12345":
#                     st.session_state["logged_in"] = True
#                     st.success("Login berhasil! Memuat sistem...")
#                     st.rerun() # Refresh halaman otomatis
#                 else:
#                     st.error("⚠️ Username atau password salah!")
# 
# # 3. LOGIKA JIKA SUDAH LOGIN (TAMPILKAN APLIKASI ASLI)
# else:
#     # --- MULAI DARI SINI ADALAH KODE ASLI TANPA ADA YANG DIUBAH ---
# 
#     # Tombol Logout (Fitur tambahan kecil agar mudah keluar)
#     colA, colB = st.columns([8, 1])
#     with colB:
#         if st.button("🚪 Logout", use_container_width=True):
#             st.session_state["logged_in"] = False
#             st.rerun()
# 
#     st.title("🎙️ TranscribX: Live Zoom Transcription & AI Summarizer")
#     st.markdown("Mesin **Web Speech API** + **AI LiteLLM Summary** untuk Notulensi Otomatis dengan UI Enterprise.")
# 
#     st.info("💡 **TIPS ZOOM:** Agar web ini bisa mendengar Zoom, pastikan mikrofon browser menggunakan **Stereo Mix** atau **VB-Cable**.")
# 
#     html_code = """
#     <!DOCTYPE html>
#     <html>
#     <head>
#         <script src="https://cdn.tailwindcss.com"></script>
# 
#         <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
# 
#         <!-- FIX 1: Memperbaiki CDN Path agar tidak 404 (Gunakan auto-resolve CDN) -->
#         <script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
#         <script src="https://cdn.jsdelivr.net/npm/markmap-lib"></script>
#         <script src="https://cdn.jsdelivr.net/npm/markmap-view"></script>
# 
#         <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
# 
#         <!-- FIX 2: html2canvas diperlukan agar tombol SIMPAN PNG berfungsi -->
#         <script src="https://html2canvas.hertzen.com/dist/html2canvas.min.js"></script>
# 
#         <style>
#             body { font-family: 'Inter', sans-serif; background: transparent; margin: 0; }
# 
#             .controls-wrapper {
#                 margin-bottom: 20px; display: flex; flex-direction: column; gap: 15px;
#                 padding: 15px; background: #f1f5f9; border-radius: 16px;
#                 box-shadow: inset 0 2px 4px 0 rgba(0,0,0,0.06);
#             }
# 
#             .controls-line { display: flex; align-items: center; gap: 15px; flex-wrap: wrap; }
# 
#             .visualizer-container {
#                 width: 100%; height: 80px; border-radius: 12px; overflow: hidden;
#                 background: #111827; position: relative;
#             }
#             #visualizer { width: 100%; height: 100%; display: block; }
# 
#             .transcript-box {
#                 border: 2px solid #cbd5e1; padding: 20px; border-radius: 16px;
#                 height: 300px; overflow-y: auto; background: white;
#                 box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1); margin-bottom: 20px;
#                 scroll-behavior: smooth;
#             }
# 
#             .btn-custom {
#                 background: #3b82f6; color: white; padding: 10px 20px; border: none;
#                 border-radius: 8px; cursor: pointer; font-weight: bold; transition: all 0.2s;
#                 display: flex; align-items: center; gap: 8px; font-size: 14px;
#             }
#             .btn-custom:hover { background: #2563eb; }
#             .btn-stop { background: #ef4444; }
#             .btn-stop:hover { background: #dc2626; }
#             .btn-ai { background: #8b5cf6; }
#             .btn-ai:hover { background: #7c3aed; }
#             .btn-custom:disabled { background: #94a3b8; cursor: not-allowed; }
# 
#             .btn-secondary { background: #e2e8f0; color: #334155; }
#             .btn-secondary:hover { background: #cbd5e1; }
# 
#             select.btn-secondary, input.api-input { outline: none; border: 1px solid #cbd5e1; padding: 10px; border-radius: 8px; font-family: inherit; }
#             input.api-input { flex-grow: 1; min-width: 250px; }
# 
#             .line-final { margin-bottom: 12px; padding: 12px; background: #f1f5f9; border-radius: 8px; border-left: 4px solid #3b82f6; font-size: 14px; line-height: 1.5; }
#             .line-interim { margin-bottom: 12px; padding: 12px; background: #f8fafc; border-radius: 8px; border-left: 4px solid #cbd5e1; font-size: 14px; opacity: 0.7; font-style: italic; }
#             .timestamp { font-weight: bold; color: #64748b; margin-right: 8px; font-size: 12px; }
#             .reconnecting { color: #ef4444; font-size: 12px; margin-left: 8px; font-style: italic; }
# 
#             #audioContainer { display: flex; flex-direction: column; gap: 10px; }
#             .audio-item { display: flex; align-items: center; gap: 15px; padding: 15px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; }
# 
#             .fade-in { animation: fadeIn 0.5s ease-in-out; }
#             @keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }
# 
#             .markmap-svg-container { width: 100%; height: 400px; display: block; }
#             .markmap-svg-container svg { width: 100%; height: 100%; }
# 
#             .mermaid-container { width: 100%; min-height: 200px; display: flex; justify-content: center; }
#         </style>
#     </head>
#     <body>
#         <div class="controls-wrapper">
#             <div class="controls-line">
#                 <select id="langSelect" class="btn-custom btn-secondary" title="Pilih Bahasa">
#                     <option value="id-ID">🇮🇩 ID (Indonesia)</option>
#                     <option value="en-US">🇬🇧 EN (English)</option>
#                 </select>
# 
#                 <button id="startBtn" class="btn-custom">🚀 START CAPTURE</button>
#                 <button id="stopBtn" class="btn-custom btn-stop" disabled>⏹️ STOP</button>
# 
#                 <div style="display: flex; align-items: center; gap: 8px; margin-left: auto;">
#                     <div id="indicator" style="width: 12px; height: 12px; border-radius: 50%; background: #cbd5e1;"></div>
#                     <span id="status" style="font-weight: bold; font-size: 14px; color: #64748b;">Standby...</span>
#                 </div>
#             </div>
# 
#             <div class="visualizer-container">
#                 <canvas id="visualizer"></canvas>
#             </div>
# 
#             <div class="controls-line" style="background: #e2e8f0; padding: 10px; border-radius: 10px;">
#                 <span style="font-size: 14px; font-weight: bold;">🔑 LiteLLM API Key:</span>
#                 <input type="password" id="apiKeyInput" class="api-input" placeholder="sk-...">
#                 <button id="aiBtn" class="btn-custom btn-ai">✨ Generate AI Summary & Mindmap</button>
#             </div>
# 
#             <div class="controls-line" style="justify-content: flex-end;">
#                 <button id="copyBtn" class="btn-custom btn-secondary">📋 Copy Text</button>
#                 <button id="clearBtn" class="btn-custom btn-secondary">🗑️ Clear</button>
#                 <button id="downloadTxtBtn" class="btn-custom" style="background: #10b981;">📝 Save TXT</button>
#             </div>
#         </div>
# 
#         <div id="transcriptBox" class="transcript-box">
#             <div id="placeholder" style="text-align: center; color: #94a3b8; margin-top: 100px;">
#                 Suara yang ditangkap akan muncul di sini...
#             </div>
#         </div>
# 
#         <div id="aiContent" class="w-full"></div>
# 
#         <h3 style="margin-bottom: 10px; font-size: 16px; margin-top: 20px;">🎧 Arsip Rekaman Suara</h3>
#         <div id="audioContainer"></div>
# 
#         <script>
#             // Konfigurasi ketat Mermaid agar tidak mudah crash
#             mermaid.initialize({
#                 startOnLoad: false,
#                 theme: 'default',
#                 securityLevel: 'loose',
#                 flowchart: { htmlLabels: true, curve: 'basis' }
#             });
# 
#             const startBtn = document.getElementById('startBtn');
#             const stopBtn = document.getElementById('stopBtn');
#             const copyBtn = document.getElementById('copyBtn');
#             const clearBtn = document.getElementById('clearBtn');
#             const downloadTxtBtn = document.getElementById('downloadTxtBtn');
#             const aiBtn = document.getElementById('aiBtn');
#             const apiKeyInput = document.getElementById('apiKeyInput');
#             const aiContent = document.getElementById('aiContent');
#             const langSelect = document.getElementById('langSelect');
#             const status = document.getElementById('status');
#             const indicator = document.getElementById('indicator');
#             const transcriptBox = document.getElementById('transcriptBox');
#             const audioContainer = document.getElementById('audioContainer');
#             const visualizer = document.getElementById('visualizer');
#             const canvasCtx = visualizer.getContext('2d');
# 
#             let recognition, mediaRecorder, audioChunks = [], audioStream, isRecording = false;
#             let lastAiData = null;
#             let audioContext, analyser, dataArray, bufferLength, drawVisual;
# 
#             if (!('webkitSpeechRecognition' in window) && !('SpeechRecognition' in window)) {
#                 status.innerText = "Browser tidak mendukung Speech API.";
#             } else {
#                 const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
#                 recognition = new SpeechRecognition();
#                 recognition.continuous = true;
#                 recognition.interimResults = true;
# 
#                 let currentInterimDiv = null;
#                 let lastFinalText = "";
# 
#                 function getTimestamp() {
#                     const now = new Date();
#                     return `[${now.getHours().toString().padStart(2, '0')}:${now.getMinutes().toString().padStart(2, '0')}:${now.getSeconds().toString().padStart(2, '0')}]`;
#                 }
# 
#                 recognition.onresult = (event) => {
#                     let interimTranscript = '';
#                     let finalTranscript = '';
# 
#                     for (let i = event.resultIndex; i < event.results.length; ++i) {
#                         if (event.results[i].isFinal) finalTranscript += event.results[i][0].transcript;
#                         else interimTranscript += event.results[i][0].transcript;
#                     }
# 
#                     if (finalTranscript) {
#                         if (finalTranscript.trim() === lastFinalText.trim()) return;
#                         lastFinalText = finalTranscript;
# 
#                         const timeStr = getTimestamp();
#                         if (currentInterimDiv) {
#                             currentInterimDiv.className = 'line-final';
#                             currentInterimDiv.innerHTML = `<span class="timestamp">${timeStr}</span> ${finalTranscript}`;
#                             currentInterimDiv = null;
#                         } else {
#                             const line = document.createElement('div');
#                             line.className = 'line-final';
#                             line.innerHTML = `<span class="timestamp">${timeStr}</span> ${finalTranscript}`;
#                             transcriptBox.appendChild(line);
#                         }
#                         transcriptBox.scrollTop = transcriptBox.scrollHeight;
#                     } else if (interimTranscript) {
#                         if (!currentInterimDiv) {
#                             currentInterimDiv = document.createElement('div');
#                             currentInterimDiv.className = 'line-interim';
#                             transcriptBox.appendChild(currentInterimDiv);
#                         }
#                         currentInterimDiv.innerText = interimTranscript;
#                         transcriptBox.scrollTop = transcriptBox.scrollHeight;
#                     }
#                 };
# 
#                 recognition.onend = () => {
#                     if (currentInterimDiv && currentInterimDiv.innerText.trim() !== '') {
#                         const timeStr = getTimestamp();
#                         currentInterimDiv.className = 'line-final';
#                         currentInterimDiv.innerHTML = `<span class="timestamp">${timeStr}</span> ${currentInterimDiv.innerText} <span class="reconnecting">[System Refreshing...]</span>`;
#                         currentInterimDiv = null;
#                     }
#                     if (isRecording) { try { recognition.start(); } catch(e){} }
#                 };
# 
#                 function setupVisualizer(stream) {
#                     audioContext = new (window.AudioContext || window.webkitAudioContext)();
#                     const source = audioContext.createMediaStreamSource(stream);
#                     analyser = audioContext.createAnalyser();
#                     analyser.fftSize = 256;
#                     bufferLength = analyser.frequencyBinCount;
#                     dataArray = new Uint8Array(bufferLength);
#                     source.connect(analyser);
#                 }
# 
#                 function drawVisualizer() {
#                     canvasCtx.clearRect(0, 0, visualizer.width, visualizer.height);
#                     if (analyser) analyser.getByteFrequencyData(dataArray);
#                     const barWidth = (visualizer.width / bufferLength) * 2.5;
#                     let barHeight;
#                     let x = 0;
#                     for(let i = 0; i < bufferLength; i++) {
#                         barHeight = dataArray[i];
#                         canvasCtx.fillStyle = 'rgb(' + (barHeight + 100) + ', 50, 255)';
#                         canvasCtx.shadowBlur = 10;
#                         canvasCtx.shadowColor = '#3b82f6';
#                         const y = (visualizer.height / 2) - (barHeight / 2);
#                         canvasCtx.beginPath();
#                         canvasCtx.roundRect(x, y, barWidth, barHeight, 5);
#                         canvasCtx.fill();
#                         x += barWidth + 1;
#                     }
#                     drawVisual = requestAnimationFrame(drawVisualizer);
#                 }
# 
#                 startBtn.onclick = async () => {
#                     try {
#                         lastFinalText = "";
#                         recognition.lang = langSelect.value;
#                         audioStream = await navigator.mediaDevices.getDisplayMedia({ video: true, audio: true });
#                         audioChunks = [];
#                         mediaRecorder = new MediaRecorder(audioStream);
#                         mediaRecorder.ondataavailable = e => { if (e.data.size > 0) audioChunks.push(e.data); };
#                         mediaRecorder.onstop = () => {
#                             const blob = new Blob(audioChunks, { type: 'audio/webm' });
#                             const audioUrl = URL.createObjectURL(blob);
#                             const fileName = 'Rekaman_TranscribX_' + new Date().getTime() + '.webm';
# 
#                             const audioItem = document.createElement('div');
#                             audioItem.className = 'audio-item';
#                             const audioEl = document.createElement('audio'); audioEl.controls = true; audioEl.src = audioUrl;
#                             const dlLink = document.createElement('a'); dlLink.href = audioUrl; dlLink.download = fileName; dlLink.innerText = '💾 Download Audio'; dlLink.className = 'btn-custom';
# 
#                             audioItem.appendChild(audioEl); audioItem.appendChild(dlLink);
#                             audioContainer.prepend(audioItem);
#                         };
# 
#                         setupVisualizer(audioStream);
#                         mediaRecorder.start(); recognition.start(); drawVisualizer();
# 
#                         isRecording = true;
#                         status.innerText = "Merekam (" + (langSelect.value === 'id-ID' ? 'ID' : 'EN') + ")...";
#                         indicator.style.background = "#ef4444"; indicator.style.boxShadow = "0 0 10px #ef4444";
#                         startBtn.disabled = true; stopBtn.disabled = false; langSelect.disabled = true;
#                         if(document.getElementById('placeholder')) document.getElementById('placeholder').style.display = 'none';
#                     } catch(err) {
#                         console.error("Gagal akses mic:", err); status.innerText = "Izin Mic Ditolak!";
#                     }
#                 };
# 
#                 stopBtn.onclick = () => {
#                     isRecording = false;
#                     recognition.stop();
#                     if (mediaRecorder && mediaRecorder.state !== 'inactive') mediaRecorder.stop();
#                     if (audioStream) audioStream.getTracks().forEach(track => track.stop());
# 
#                     cancelAnimationFrame(drawVisual);
#                     if (audioContext) audioContext.close();
#                     canvasCtx.clearRect(0, 0, visualizer.width, visualizer.height);
# 
#                     status.innerText = "Standby...";
#                     indicator.style.background = "#cbd5e1"; indicator.style.boxShadow = "none";
#                     startBtn.disabled = false; stopBtn.disabled = true; langSelect.disabled = false;
#                 };
# 
#                 function getTranscriptText() {
#                     const lines = transcriptBox.querySelectorAll('.line-final');
#                     if (lines.length === 0) return "";
#                     return Array.from(lines).map(line => line.innerText).join('\\n');
#                 }
# 
#                 copyBtn.onclick = () => {
#                     const text = getTranscriptText();
#                     if (!text) return alert("Belum ada teks untuk dicopy!");
#                     navigator.clipboard.writeText(text).then(() => {
#                         const originalText = copyBtn.innerText;
#                         copyBtn.innerText = "✅ Copied!";
#                         setTimeout(() => copyBtn.innerText = originalText, 2000);
#                     });
#                 };
# 
#                 downloadTxtBtn.onclick = () => {
#                     const text = getTranscriptText();
#                     if (!text) return alert("Belum ada teks untuk disimpan!");
#                     const blob = new Blob([text], { type: 'text/plain' });
#                     const url = URL.createObjectURL(blob);
#                     const a = document.createElement('a');
#                     a.href = url; a.download = 'Notulensi_TranscribX_' + new Date().getTime() + '.txt';
#                     a.click();
#                 };
# 
#                 clearBtn.onclick = () => {
#                     if(confirm("Yakin ingin menghapus semua teks di layar?")) {
#                         transcriptBox.innerHTML = '<div id="placeholder" style="text-align: center; color: #94a3b8; margin-top: 100px;">Suara yang ditangkap akan muncul di sini...</div>';
#                         lastFinalText = "";
#                         aiContent.innerHTML = "";
#                     }
#                 };
# 
#                 // FUNGSI HELPER UNTUK MENGUNDUH NOTULENSI
#                 window.downloadMinutes = () => {
#                     if (!lastAiData) return alert("Belum ada data notulensi AI!");
#                     const txtContent = `NOTULENSI RESMI\n=================================\nAGENDA: ${lastAiData.notulensi_rapat.agenda}\nPESERTA: ${lastAiData.notulensi_rapat.peserta.join(', ')}\n\nJALANNYA DISKUSI:\n${lastAiData.notulensi_rapat.jalannya_diskusi}\n\nKEPUTUSAN / KESIMPULAN:\n${lastAiData.notulensi_rapat.keputusan.map(k=> "- "+k).join('\\n')}`;
#                     const blob = new Blob([txtContent], { type: 'text/plain' });
#                     const url = URL.createObjectURL(blob);
#                     const a = document.createElement('a');
#                     a.href = url; a.download = 'AI_Notulensi_Rapat.txt';
#                     a.click();
#                 };
# 
#                 // FUNGSI HELPER DOWNLOAD GAMBAR (MINDMAP/MERMAID)
#                 window.downloadImage = (elementId, filename) => {
#                     const el = document.getElementById(elementId);
#                     if(!el) return alert("Elemen tidak ditemukan!");
# 
#                     // Menambahkan delay kecil agar rendering DOM SVG / D3.js selesai dengan baik sebelum difoto
#                     setTimeout(() => {
#                         html2canvas(el, { backgroundColor: "#ffffff", scale: 2 }).then(canvas => {
#                             const link = document.createElement('a');
#                             link.download = filename + '.png';
#                             link.href = canvas.toDataURL('image/png');
#                             link.click();
#                         }).catch(err => alert("Gagal download gambar: " + err));
#                     }, 300);
#                 };
# 
#                 // LOGIKA AI SUMMARIZER (DENGAN MARKMAP & MERMAID SINTAKS KETAT & KEPUTUSAN KAYA)
#                 aiBtn.onclick = async () => {
#                     const transcript = getTranscriptText();
#                     const apiKey = apiKeyInput.value.trim();
# 
#                     if (!apiKey) { alert("⚠️ Masukkan API Key LiteLLM/Gemini terlebih dahulu."); apiKeyInput.focus(); return; }
#                     if (!transcript) { alert("⚠️ Transkrip masih kosong."); return; }
# 
#                     const originalText = aiBtn.innerHTML;
#                     aiBtn.innerHTML = "⏳ AI sedang memproses JSON...";
#                     aiBtn.disabled = true;
#                     aiContent.innerHTML = `
#                         <div class="p-8 bg-purple-50 rounded-[2.5rem] border border-purple-200 shadow-sm text-center fade-in mt-6">
#                             <p class="text-purple-600 font-bold animate-pulse">Memproses Notulensi, Markmap & Mermaid... Mohon tunggu (±15 detik).</p>
#                         </div>`;
# 
#                     // FIX 3 & 4: PROMPT DIUBAH AGAR "KEPUTUSAN" KAYA ISI DAN MERMAID BERBENTUK MINDMAP POHON
#                     const prompt = `Anda adalah Ahli Pembuat Notulensi dan Visual Mapping.
#                         Analisis transkrip rapat berikut dan hasilkan JSON.
# 
#                         ATURAN KEPUTUSAN PENTING (CRITICAL):
#                         Walaupun rapat hanya bersifat diskusi, analisa, atau pemaparan materi (tidak ada keputusan formal), Anda WAJIB merumuskan poin-poin kesimpulan utama, key takeaways, atau insight terpenting ke dalam array "keputusan". JANGAN PERNAH mengisi dengan kalimat "Tidak ada keputusan".
# 
#                         ATURAN MERMAID MINDMAP (SANGAT KETAT ANTI ERROR):
#                         1. JANGAN gunakan markdown block (\`\`\`mermaid). Langsung tulis kode murni 'graph LR' (Kiri ke Kanan).
#                         2. Buat struktur pohon (Mindmap) yang berpusat pada satu Root Node di kiri, menyebar rapi ke cabang-cabang di kanannya. Batasi maksimal 3 level kedalaman agar diagram tidak ruwet.
#                         3. ID Node WAJIB hanya huruf/angka tanpa spasi (A1, B1, Cabang2).
#                         4. Label Node WAJIB diapit tanda kutip dua ("). Contoh Benar: A1["Teks Label"].
#                         5. DILARANG menggunakan karakter kurung ( ) { } [ ] di dalam teks label.
# 
#                         ATURAN MARKMAP:
#                         1. JANGAN gunakan markdown block (\`\`\`markdown). Langsung tulis kode murninya.
#                         2. Gunakan # untuk Judul Utama (Root), ## untuk Sub-Topik Utama, dan - untuk poin detail (Maksimal 3 level).
# 
#                         Transkrip Rapat:
#                         "${transcript}"`;
# 
#                     const payload = {
#                         "model": "gemini/gemini-2.5-flash",
#                         "messages": [{ "role": "user", "content": prompt }],
#                         "temperature": 0.2,
#                         "response_format": {
#                             "type": "json_schema",
#                             "json_schema": {
#                                 "name": "meeting_summary",
#                                 "strict": true,
#                                 "schema": {
#                                     "type": "object",
#                                     "properties": {
#                                         "ringkasan_eksekutif": { "type": "string" },
#                                         "notulensi_rapat": {
#                                             "type": "object",
#                                             "properties": {
#                                                 "agenda": { "type": "string" },
#                                                 "peserta": { "type": "array", "items": { "type": "string" } },
#                                                 "jalannya_diskusi": { "type": "string" },
#                                                 "keputusan": { "type": "array", "items": { "type": "string" }, "description": "Wajib diisi dengan kesimpulan utama atau take-aways diskusi jika tidak ada keputusan formal" }
#                                             },
#                                             "required": ["agenda", "peserta", "jalannya_diskusi", "keputusan"],
#                                             "additionalProperties": false
#                                         },
#                                         "visual_mindmap": { "type": "string", "description": "Kode murni Mermaid graph LR berbentuk struktur pohon berpusat" },
#                                         "markmap_code": { "type": "string", "description": "Kode murni Markdown untuk Markmap berbentuk struktur pohon" }
#                                     },
#                                     "required": ["ringkasan_eksekutif", "notulensi_rapat", "visual_mindmap", "markmap_code"],
#                                     "additionalProperties": false
#                                 }
#                             }
#                         }
#                     };
# 
#                     try {
#                         const response = await fetch("https://litellm.koboi2026.biz.id/v1/chat/completions", {
#                             method: "POST",
#                             headers: { "Authorization": "Bearer " + apiKey, "Content-Type": "application/json" },
#                             body: JSON.stringify(payload)
#                         });
# 
#                         const resJson = await response.json();
# 
#                         if (resJson.choices && resJson.choices[0].message.content) {
#                             const data = JSON.parse(resJson.choices[0].message.content);
#                             lastAiData = data;
# 
#                             const reportDiv = document.createElement('div');
#                             reportDiv.className = "fade-in space-y-6 mt-6 mb-10";
# 
#                             // 1. BLOK NOTULENSI
#                             let notulensiHtml = `
#                                 <div class="p-8 bg-slate-50 rounded-[2.5rem] border border-slate-200 shadow-sm relative overflow-hidden mb-6">
#                                     <div class="absolute top-0 right-0 p-4 opacity-5 text-4xl">📝</div>
#                                     <h5 class="text-[10px] font-black text-slate-500 uppercase tracking-widest mb-4">Notulensi Resmi Rapat</h5>
#                                     <div class="space-y-4 text-xs text-slate-700 leading-relaxed">
#                                         <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
#                                             <div><p class="font-black text-blue-600 uppercase text-[9px] mb-1">Agenda:</p><p class="font-medium">${data.notulensi_rapat.agenda || '-'}</p></div>
#                                             <div><p class="font-black text-blue-600 uppercase text-[9px] mb-1">Peserta:</p><p class="font-medium">${data.notulensi_rapat.peserta.join(', ') || '-'}</p></div>
#                                         </div>
#                                         <div><p class="font-black text-blue-600 uppercase text-[9px] mb-1">Jalannya Diskusi:</p><p class="bg-white/50 p-3 rounded-xl border border-slate-100">${data.notulensi_rapat.jalannya_diskusi}</p></div>
#                                         <div><p class="font-black text-blue-600 uppercase text-[9px] mb-1">Keputusan / Kesimpulan Utama:</p><ul class="list-disc ml-4 space-y-1 font-bold text-slate-800">${data.notulensi_rapat.keputusan.map(k => `<li>${k}</li>`).join('')}</ul></div>
#                                     </div>
#                                     <button onclick="downloadMinutes()" class="mt-6 w-full bg-slate-800 text-white text-[10px] font-black py-3 rounded-xl hover:bg-black transition-all flex items-center justify-center gap-2">
#                                         <span>📥</span> DOWNLOAD NOTULENSI (.TXT)
#                                     </button>
#                                 </div>
#                             `;
# 
#                             // 2. BLOK VISUALISASI MINDMAP (DUAL ENGINE)
#                             // SANITIZER MERMAID (Menghindari Syntax Error)
#                             let rawMermaid = data.visual_mindmap.replace(/```mermaid/gi, '').replace(/```/g, '').trim();
#                             rawMermaid = rawMermaid.replace(/\[([^"\]]+)\]/g, '["$1"]'); // Tambah kutip dua jika hilang
#                             rawMermaid = rawMermaid.replace(/\(/g, '[').replace(/\)/g, ']'); // Hindari kurung bulat
#                             if (!rawMermaid.toLowerCase().includes('graph')) rawMermaid = "graph LR\\n" + rawMermaid;
# 
#                             // SANITIZER MARKMAP
#                             let rawMarkmap = data.markmap_code.replace(/```markdown/gi, '').replace(/```/g, '').trim();
# 
#                             let visualizationHtml = `
#                                 <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
#                                     <!-- MARKMAP CARD -->
#                                     <div class="p-6 bg-white rounded-3xl border border-slate-200 shadow-sm flex flex-col">
#                                         <h5 class="text-[10px] font-black text-emerald-600 uppercase tracking-widest mb-4 flex items-center gap-2"><span>🌿</span> Markmap (Markdown)</h5>
#                                         <div id="markmap-capture-area" class="flex-grow bg-slate-50 border border-slate-100 rounded-2xl overflow-hidden markmap-svg-container relative p-2" style="min-height: 400px;">
#                                         </div>
#                                         <div class="mt-4 flex gap-2">
#                                             <button onclick="downloadImage('markmap-capture-area', 'Markmap_Mindmap')" class="w-full bg-emerald-600 text-white text-[10px] font-bold py-2 rounded-xl hover:bg-emerald-700 transition-all">📥 SIMPAN MARKMAP (PNG)</button>
#                                         </div>
#                                         <details class="mt-4 text-[10px]">
#                                             <summary class="cursor-pointer text-slate-400 font-bold hover:text-slate-600">Lihat Source Markdown</summary>
#                                             <pre class="mt-2 p-3 bg-slate-800 text-green-400 rounded-lg overflow-x-auto whitespace-pre-wrap">${rawMarkmap}</pre>
#                                         </details>
#                                     </div>
# 
#                                     <!-- MERMAID CARD -->
#                                     <div class="p-6 bg-white rounded-3xl border border-slate-200 shadow-sm flex flex-col">
#                                         <h5 class="text-[10px] font-black text-indigo-600 uppercase tracking-widest mb-4 flex items-center gap-2"><span>🌊</span> Mermaid.js (Mindmap)</h5>
#                                         <div id="mermaid-capture-area" class="flex-grow bg-slate-50 border border-slate-100 rounded-2xl overflow-x-auto p-4 mermaid-container">
#                                             <div class="mermaid">${rawMermaid}</div>
#                                         </div>
#                                         <div class="mt-4 flex gap-2">
#                                             <button onclick="downloadImage('mermaid-capture-area', 'Mermaid_Mindmap')" class="w-full bg-indigo-600 text-white text-[10px] font-bold py-2 rounded-xl hover:bg-indigo-700 transition-all">📥 SIMPAN MERMAID (PNG)</button>
#                                         </div>
#                                         <details class="mt-4 text-[10px]">
#                                             <summary class="cursor-pointer text-slate-400 font-bold hover:text-slate-600">Lihat Source Mermaid</summary>
#                                             <pre class="mt-2 p-3 bg-slate-800 text-blue-400 rounded-lg overflow-x-auto whitespace-pre-wrap">${rawMermaid}</pre>
#                                         </details>
#                                     </div>
#                                 </div>
#                             `;
# 
#                             reportDiv.innerHTML = notulensiHtml + visualizationHtml;
#                             aiContent.innerHTML = "";
#                             aiContent.appendChild(reportDiv);
# 
#                             // Eksekusi Render Markmap
#                             try {
#                                 // Validasi pencegahan jika CDN gagal dimuat
#                                 if (!window.markmap) throw new Error("Library Markmap gagal dimuat dari CDN. Cek koneksi internet.");
# 
#                                 const { Transformer, Markmap } = window.markmap;
#                                 const transformer = new Transformer();
#                                 const { root } = transformer.transform(rawMarkmap);
# 
#                                 const svgContainer = document.getElementById('markmap-capture-area');
#                                 svgContainer.innerHTML = '<svg id="markmap-svg" style="width:100%; height:400px; min-height:400px;"></svg>';
# 
#                                 // Gunakan elemen DOM langsung (lebih aman untuk D3.js) alih-alih string ID
#                                 const svgElement = document.getElementById('markmap-svg');
#                                 Markmap.create(svgElement, null, root);
# 
#                             } catch (e) {
#                                 console.error("Markmap Render Error:", e);
#                                 document.getElementById('markmap-capture-area').innerHTML = `<p class="text-red-500 font-bold p-4 text-xs">Error merender Markmap: ${e.message}</p>`;
#                             }
# 
#                             // Eksekusi Render Mermaid
#                             setTimeout(() => {
#                                 try { mermaid.run({ querySelector: '.mermaid' }); }
#                                 catch (e) {
#                                     console.error("Mermaid Render Error:", e);
#                                     document.querySelector('.mermaid').innerHTML = `<p class="text-red-500 text-xs">Error merender flowchart. Cek Source Code di bawah.</p>`;
#                                 }
#                             }, 500);
# 
#                         } else if (resJson.error) {
#                             aiContent.innerHTML = `<p class="text-red-500 font-bold p-4 bg-red-50 rounded-xl mt-6">Error: ${resJson.error.message}</p>`;
#                         }
# 
#                     } catch (err) {
#                         aiContent.innerHTML = `<p class="text-red-500 font-bold p-4 bg-red-50 rounded-xl mt-6">Koneksi Gagal: Cek API Key. Detail: ${err.message}</p>`;
#                     } finally {
#                         aiBtn.innerHTML = originalText; aiBtn.disabled = false;
#                         aiContent.scrollIntoView({ behavior: 'smooth' });
#                     }
#                 };
#             }
#         </script>
#     </body>
#     </html>
#     """
# 
#     components.html(html_code, height=1200, scrolling=True)

from google.colab import userdata
from pyngrok import ngrok

# 1. Mengambil token dari brankas "Secrets" Colab
NGROK_TOKEN = userdata.get('NGROK_TOKEN')
ngrok.set_auth_token(NGROK_TOKEN)

# 2. Bersihkan sesi ngrok sebelumnya
ngrok.kill()

# 3. Jalankan aplikasi Streamlit di background
get_ipython().system_raw('streamlit run app.py &>/dev/null&')

# 4. Buat terowongan publik
public_url = ngrok.connect(8501).public_url
print("=====================================================")
print(f"🚀 KLIK LINK INI UNTUK BUKA TRANSCRIBX: {public_url}")
print("=====================================================")
